pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                withMaven (maven: 'maven3') {
                    sh 'mvn pom.xml clean package'
                }
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
    }
}